"""
Django settings for pim project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Загружаем переменные окружения из .env (если файл есть). На проде .env лежит
# рядом с проектом; локально файла может не быть — тогда работают значения по
# умолчанию ниже.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# В продакшене задаётся через переменную окружения SECRET_KEY.
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-dev-key-change-me-before-deploy",
)

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG=1 (по умолчанию для локальной разработки) / DEBUG=0 в продакшене.
DEBUG = os.getenv("DEBUG", "1") == "1"

# Список доменов через запятую, напр. "example.com,www.example.com".
ALLOWED_HOSTS = [h for h in os.getenv("ALLOWED_HOSTS", "*").split(",") if h]

# Доверенные источники для CSRF (нужно для админки не на localhost).
# Со схемой, через запятую: "http://1.2.3.4" или "https://example.com".
CSRF_TRUSTED_ORIGINS = [o for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if o]
CORS_ALLOWED_ORIGINS = [o for o in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",") if o]

# Куки только по HTTPS — включить (COOKIE_SECURE=1), когда появится домен с TLS.
SESSION_COOKIE_SECURE = os.getenv("COOKIE_SECURE", "0") == "1"
CSRF_COOKIE_SECURE = os.getenv("COOKIE_SECURE", "0") == "1"

# Если приложение за HTTPS-прокси (nginx + Let's Encrypt) — BEHIND_TLS_PROXY=1.
if os.getenv("BEHIND_TLS_PROXY") == "1":
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third-party
    'rest_framework',            # REST API
    'rest_framework.authtoken',  # токены для записи
    'drf_spectacular',           # OpenAPI 3 схема + Swagger UI (контракт для интеграции)
    'adminsortable2',   # drag-and-drop сортировка в админке
    'mptt',             # дерево категорий (вложенность + перетаскивание)
    'tinymce',          # визуальный HTML-редактор
    'image_uploader_widget',  # пакетная загрузка/превью/сортировка изображений
    'django_countries',  # справочник стран для поля «страна производства»
    'corsheaders',
    # local apps
    'catalog',
]

# Конфигурация визуального редактора (self-hosted, без облачного API-ключа)
TINYMCE_DEFAULT_CONFIG = {
    "height": 400,
    "menubar": "edit view insert format tools table",
    "plugins": "advlist autolink lists link image charmap preview anchor "
               "searchreplace visualblocks code fullscreen insertdatetime "
               "media table help wordcount",
    "toolbar": "undo redo | blocks | bold italic underline | "
               "alignleft aligncenter alignright | bullist numlist | "
               "link image table | code fullscreen | removeformat",
    "promotion": False,
    "branding": False,
    # загрузка изображений прямо в media PIM (а не только по внешней ссылке)
    "images_upload_url": "/tinymce/upload/",
    "automatic_uploads": True,
    "images_upload_credentials": True,   # слать cookie сессии вместе с загрузкой
    "paste_data_images": True,           # картинки из буфера обмена тоже загружаются
    "convert_urls": False,               # не переписывать абсолютные URL картинок
    "relative_urls": False,
}

# Django REST Framework: публичное чтение, запись по токену для staff
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "catalog.permissions.IsStaffOrReadOnly",
    ],
    # генератор OpenAPI-схемы (эндпоинты /api/schema/ и /api/docs/)
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    # Мягкая защита от скрейпинга/DoS. Ставки настраиваются в .env без правки кода.
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": os.getenv("THROTTLE_ANON", "300/min"),
        "user": os.getenv("THROTTLE_USER", "1000/min"),
    },
}

# Метаданные OpenAPI-схемы. Схема — машиночитаемый контракт каталога для
# интеграции (напр. с Ensi): GET /api/schema/ (YAML), Swagger UI на /api/docs/.
SPECTACULAR_SETTINGS = {
    "TITLE": "ProfiSfera PIM — Catalog API",
    "DESCRIPTION": (
        "Headless-каталог ProfiSfera: товары, категории, характеристики, "
        "бренды, документы, навигационные фасеты, группировки вариантов и "
        "обучение. Публичное чтение; запись — по токену staff. Ключ интеграции "
        "контента — внутренний sku. Инкрементальная выборка — параметр "
        "updated_since. Коммерческий слой (цены/остатки/клиенты) в контракт не "
        "входит."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pim.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pim.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# По умолчанию SQLite (запускается без настройки). На VPS переключаем
# на Postgres переменной окружения DB_ENGINE=postgres.

if os.getenv("DB_ENGINE") == "postgres":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "pim"),
            "USER": os.getenv("DB_USER", "pim"),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # для collectstatic на деплое

# Загружаемые файлы (изображения товаров, логотипы, PDF-документы)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Тип первичного ключа по умолчанию
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
