# Generated by Django 6.0.6 on 2026-06-09 16:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('number', models.CharField(blank=True, max_length=128, verbose_name='Номер')),
                ('file', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Файл (PDF)')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.SlugField(help_text="Машинный код для API, напр. 'color' или 'power_w'.", max_length=128, unique=True, verbose_name='Код')),
                ('type', models.CharField(choices=[('single_select', 'Список (единичный выбор)'), ('multi_select', 'Список (множественный выбор)'), ('number', 'Числовое поле'), ('text', 'Текстовое поле'), ('boolean', 'Булева (да/нет)')], max_length=20, verbose_name='Тип')),
                ('unit', models.CharField(blank=True, help_text="Напр. 'мм', 'кг'. Имеет смысл для числовых характеристик.", max_length=32, verbose_name='Единица измерения')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('categories', models.ManyToManyField(blank=True, related_name='characteristics', to='catalog.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CharacteristicOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.characteristic', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Вариант значения',
                'verbose_name_plural': 'Варианты значений',
                'ordering': ['order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, help_text='Поддерживает HTML, редактируется через визуальный редактор.', verbose_name='Полное описание (HTML)')),
                ('manufacturer_sku', models.CharField(blank=True, max_length=128, verbose_name='Артикул производителя')),
                ('gross_width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Брутто-ширина, мм')),
                ('gross_height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Брутто-высота, мм')),
                ('gross_depth_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Брутто-глубина, мм')),
                ('gross_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Брутто-масса, кг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категория')),
                ('documents', models.ManyToManyField(blank=True, related_name='products', to='catalog.document', verbose_name='Документы')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt-текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, verbose_name='Текстовое значение')),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Числовое значение')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='Булево значение')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.characteristic', verbose_name='Характеристика')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.product', verbose_name='Товар')),
                ('value_options', models.ManyToManyField(blank=True, related_name='attribute_values', to='catalog.characteristicoption', verbose_name='Выбранные варианты')),
            ],
            options={
                'verbose_name': 'Значение характеристики',
                'verbose_name_plural': 'Значения характеристик',
                'constraints': [models.UniqueConstraint(fields=('product', 'characteristic'), name='uniq_product_characteristic')],
            },
        ),
    ]
