# Generated by Django 5.2.15 on 2026-06-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, help_text='Оставьте пустым — сгенерируется автоматически из названия (транслитерацией).', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Оставьте пустым — сгенерируется автоматически из названия (транслитерацией).', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='code',
            field=models.SlugField(blank=True, help_text='Машинный код для API. Оставьте пустым — сгенерируется из названия.', max_length=128, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Оставьте пустым — сгенерируется автоматически из названия (транслитерацией).', max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
