# Generated by Django 5.2.15 on 2026-06-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_brand_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.CharField(blank=True, help_text='Код из 1С, по которому товар сопоставляется во внешних системах (Litics). Уникальный; оставьте пустым, если ещё не присвоен.', max_length=255, null=True, unique=True, verbose_name='Глобальный идентификатор (код сопоставления)'),
        ),
    ]
