# Generated by Django 5.2.15 on 2026-06-10 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название уровня')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Уровень группировки',
                'verbose_name_plural': 'Уровни группировки',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, help_text='Оставьте пустым — сгенерируется автоматически из названия (транслитерацией).', max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Группа (серия) вариантов',
                'verbose_name_plural': 'Группы (серии) вариантов',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='group_order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок отображения в переключателе вариантов.', verbose_name='Порядок в серии'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_label',
            field=models.CharField(blank=True, help_text='Короткая подпись для переключателя. Пусто — берётся название товара.', max_length=255, verbose_name='Подпись варианта'),
        ),
        migrations.CreateModel(
            name='GroupLevelValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.grouplevel', verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Значение уровня',
                'verbose_name_plural': 'Значения уровней',
                'ordering': ['order', 'value'],
            },
        ),
        migrations.AddField(
            model_name='grouplevel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='catalog.productgroup', verbose_name='Серия'),
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.productgroup', verbose_name='Серия (группа вариантов)'),
        ),
        migrations.CreateModel(
            name='ProductGroupValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='catalog.grouplevel', verbose_name='Уровень')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_values', to='catalog.product', verbose_name='Товар')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='catalog.grouplevelvalue', verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Значение группировки товара',
                'verbose_name_plural': 'Значения группировки товара',
            },
        ),
        migrations.AddConstraint(
            model_name='grouplevelvalue',
            constraint=models.UniqueConstraint(fields=('level', 'value'), name='uniq_level_value'),
        ),
        migrations.AddConstraint(
            model_name='grouplevel',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='uniq_group_level_name'),
        ),
        migrations.AddConstraint(
            model_name='productgroupvalue',
            constraint=models.UniqueConstraint(fields=('product', 'level'), name='uniq_product_group_level'),
        ),
    ]
