# Generated by Django 5.2.15 on 2026-06-11 11:42

import catalog.utils
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_grouplevel_productgroup_product_group_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Показывать у всех товаров независимо от категории. Если выключено — только у товаров категорий из списка ниже.', verbose_name='Общая характеристика'),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=django_countries.fields.CountryField(blank=True, help_text='Страна, где произведён товар.', max_length=2, verbose_name='Страна производства'),
        ),
        migrations.AddField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, help_text='Глобальный номер товара: EAN-8/13, UPC-A (12) или GTIN-14. Только цифры.', max_length=14, validators=[catalog.utils.validate_gtin], verbose_name='Штрих-код (GTIN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='tnved_code',
            field=models.CharField(blank=True, help_text='Код товарной номенклатуры ВЭД ЕАЭС (до 10 цифр). Пока вводится вручную.', max_length=10, verbose_name='Код ТН ВЭД'),
        ),
    ]
