# Generated by Django 5.2.15 on 2026-06-11 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_seed_global_characteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, help_text='Оставьте пустым — сгенерируется автоматически из названия (транслитерацией).', max_length=255, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, help_text='Идентификатор иконки для меню магазина (опционально).', max_length=64, verbose_name='Иконка')),
                ('description', models.TextField(blank=True, help_text='Текст для посадочной страницы (SEO).', verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='audiences',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.audience', verbose_name='Аудитории'),
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, help_text='Оставьте пустым — сгенерируется автоматически из названия (транслитерацией).', max_length=255, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, max_length=64, verbose_name='Иконка')),
                ('description', models.TextField(blank=True, help_text='Текст для посадочной страницы (SEO).', verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('audience', models.ForeignKey(blank=True, help_text='Чьё это направление. Пусто — общее (для всех аудиторий).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='catalog.audience', verbose_name='Аудитория')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['audience__order', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='directions',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.direction', verbose_name='Направления'),
        ),
    ]
