# Generated by Django 5.2.15 on 2026-06-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_seed_audiences_directions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
    ]
