# Generated by Django 5.2.15 on 2026-06-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_direction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BigIntegerField(default=1000000000, verbose_name='Текущее значение')),
            ],
            options={
                'verbose_name': 'Счётчик артикулов PIM',
                'verbose_name_plural': 'Счётчик артикулов PIM',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Внутренний идентификатор товара в PIM. Присваивается автоматически и не меняется.', max_length=32, null=True, unique=True, verbose_name='Артикул PIM'),
        ),
    ]
