# Generated by Django 5.2.15 on 2026-06-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_backfill_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('registration', 'Регистрационное удостоверение (РУ)'), ('declaration', 'Декларация о соответствии'), ('certificate', 'Сертификат соответствия'), ('state_registration', 'Свидетельство о госрегистрации (СГР)'), ('exemption', 'Отказное письмо'), ('ifu', 'Инструкция по применению'), ('manual', 'Руководство по эксплуатации'), ('passport', 'Паспорт изделия'), ('quality', 'Сертификат качества / анализа'), ('other', 'Другое')], default='other', max_length=32, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_perpetual',
            field=models.BooleanField(default=False, verbose_name='Бессрочный'),
        ),
        migrations.AddField(
            model_name='document',
            name='issued_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='document',
            name='issuing_authority',
            field=models.CharField(blank=True, help_text='Орган или организация, выдавшая документ (например, Росздравнадзор).', max_length=255, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='document',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Оставьте пустым, если срок не указан. Для бессрочных отметьте «Бессрочный».', null=True, verbose_name='Действует до'),
        ),
    ]
