# Generated by Django 5.2.15 on 2026-06-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_document_doc_type_document_is_perpetual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='show_to_customer',
            field=models.BooleanField(default=True, help_text='Снимите галочку для служебных характеристик (например, код 1С): они останутся в PIM, но не будут видны в витрине.', verbose_name='Показывать покупателю'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, help_text='Для внутреннего поиска и идентификации в PIM. Покупателю не показывается.', max_length=255, verbose_name='Название (внутреннее)'),
        ),
    ]
