# Generated by Django 5.2.15 on 2026-06-24 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_characteristic_show_to_customer_alter_document_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(choices=[('bool_checkbox', 'Булева: один чекбокс (= «Да»)'), ('bool_yesno', 'Булева: Да / Нет'), ('number_range', 'Число: диапазон «от–до»'), ('number_buckets', 'Число: корзины-чекбоксы'), ('select_checkbox', 'Список: чекбоксы значений')], max_length=32, verbose_name='Вид фильтра')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Необязательно. Подпись: {"label": "Объём"}. Корзины для числа: {"buckets": [{"max": 20}, {"min": 20, "max": 40}, {"min": 40}]}.', verbose_name='Доп. настройки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='catalog.category', verbose_name='Категория')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_configs', to='catalog.characteristic', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Фильтр категории',
                'verbose_name_plural': 'Фильтры категории',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('category', 'characteristic'), name='uniq_category_characteristic_filter')],
            },
        ),
    ]
