# Generated by Django 5.2.15 on 2026-06-25 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_categoryfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.FileField(blank=True, help_text='Растровое изображение или SVG. Для логотипов предпочтителен SVG — он чёткий на любом размере.', null=True, upload_to='brands/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp', 'gif'])], verbose_name='Логотип'),
        ),
    ]
