# Generated by Django 5.2.15 on 2026-07-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_rebuild_category_mptt'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='admin_label',
            field=models.CharField(blank=True, help_text='Служебная пометка, видна только в админке (покупатель её не видит). Различать одноимённые характеристики, напр. «Серия» для хирургии и «Серия» для терапии.', max_length=255, verbose_name='Внутреннее пояснение'),
        ),
    ]
