# Generated by Django 5.2.15 on 2026-07-05 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_group_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы (справочник)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name='Контакты')),
                ('erp_settings', models.JSONField(blank=True, default=dict, help_text='Служебные параметры интеграции с ERP продавца (задел на будущее).', verbose_name='Настройки ERP')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('regions', models.ManyToManyField(blank=True, help_text='Какие регионы обслуживает склад. Пусто — продаёт по всей стране.', related_name='warehouses', to='catalog.region', verbose_name='Обслуживаемые регионы')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='catalog.seller', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['seller__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_code', models.CharField(blank=True, help_text='Идентификатор для синхронизации остатка/цены со стороны продавца.', max_length=255, verbose_name='Код в ERP продавца')),
                ('stock_qty', models.PositiveIntegerField(default=0, verbose_name='Остаток (базовых единиц)')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Опциональная цена склада из ERP. Цены для покупателя задаются в условиях продажи ниже.', max_digits=12, null=True, verbose_name='Справочная цена (из ERP)')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Синхронизировано')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='catalog.product', verbose_name='Товар')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='catalog.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Торговое предложение',
                'verbose_name_plural': 'Торговые предложения',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='OfferTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('individuals', 'Физические лица'), ('clinics', 'Клиники'), ('distributors', 'Дистрибьюторы'), ('government', 'Госзакупки')], max_length=20, verbose_name='Канал продаж')),
                ('unit_name', models.CharField(default='Штука', max_length=100, verbose_name='Единица продажи')),
                ('unit_base_qty', models.PositiveIntegerField(default=1, help_text='Штука = 1; коробка = число товаров в оптовой коробке.', verbose_name='Базовых единиц в единице продажи')),
                ('step', models.PositiveIntegerField(default=1, verbose_name='Шаг (в единицах продажи)')),
                ('min_qty', models.PositiveIntegerField(default=1, verbose_name='Минимум в заказе (в единицах продажи)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за единицу продажи')),
                ('price_floor', models.DecimalField(blank=True, decimal_places=2, help_text='Жёсткий порог: ниже этой цены синхронизация опускать не имеет права.', max_digits=12, null=True, verbose_name='Мин. цена (не опускать)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='catalog.offer', verbose_name='Предложение')),
            ],
            options={
                'verbose_name': 'Условие продажи',
                'verbose_name_plural': 'Условия продажи (каналы × единицы)',
                'ordering': ['channel', 'unit_name'],
                'constraints': [models.UniqueConstraint(fields=('offer', 'channel', 'unit_name'), name='uniq_offer_channel_unit')],
            },
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('warehouse', 'product'), name='uniq_warehouse_product'),
        ),
    ]
