# Generated by Django 5.2.15 on 2026-07-07 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_remove_product_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='Пароль (хеш)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты (покупатели)',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('segment', models.CharField(choices=[('clinics', 'Клиники'), ('distributors', 'Дистрибьюторы'), ('government', 'Госзакупки')], help_text='Определяет, какой оптовый канал видят представители этого юрлица.', max_length=20, verbose_name='Сегмент (канал цен)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридические лица',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Подтверждён')], default='approved', help_text='Только «Подтверждён» даёт клиенту оптовые цены сегмента.', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='catalog.client', verbose_name='Клиент')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='catalog.legalentity', verbose_name='Юридическое лицо')),
            ],
            options={
                'verbose_name': 'Привязка клиента к юрлицу',
                'verbose_name_plural': 'Привязки клиентов к юрлицам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='legal_entities',
            field=models.ManyToManyField(blank=True, related_name='clients', through='catalog.ClientMembership', to='catalog.legalentity', verbose_name='Юридические лица'),
        ),
        migrations.AddConstraint(
            model_name='clientmembership',
            constraint=models.UniqueConstraint(fields=('client', 'legal_entity'), name='uniq_client_legalentity'),
        ),
    ]
