# Generated by Django 5.2.15 on 2026-07-07 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Ключ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='catalog.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Токен клиента',
                'verbose_name_plural': 'Токены клиентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
