# Generated by Django 5.2.15 on 2026-07-07 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_client_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('products', models.ManyToManyField(blank=True, help_text='Карточки этих товаров покажут блок обучения. Своя группировка, независимая от серии.', related_name='courses', to='catalog.product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Обучение (курс)',
                'verbose_name_plural': 'Обучение (курсы)',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('slides', 'Слайды'), ('video', 'Видео')], default='slides', max_length=10, verbose_name='Тип')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('video_url', models.URLField(blank=True, help_text='Для типа «Видео»: URL для вставки через iframe (embed-ссылка YouTube/RuTube).', verbose_name='Ссылка на видео (embed)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='catalog.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Модуль курса',
                'verbose_name_plural': 'Модули курса',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, help_text='Текст слайда, редактируется визуально.', verbose_name='Содержимое (HTML)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='catalog.coursemodule', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['order', 'id'],
            },
        ),
    ]
