# Generated by Django 5.2.15 on 2026-07-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='body',
            field=models.TextField(blank=True, help_text='Для типа «Лонгрид»: оформленная статья (визуальный редактор).', verbose_name='Текст лонгрида (HTML)'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='kind',
            field=models.CharField(choices=[('slides', 'Слайды'), ('video', 'Видео'), ('longread', 'Лонгрид')], default='slides', max_length=10, verbose_name='Тип'),
        ),
    ]
