# Generated by Django 5.2.15 on 2026-07-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_course_longread'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='entry_path',
            field=models.CharField(blank=True, default='', help_text='Относительный путь до входного HTML внутри распакованного пакета.', max_length=500, verbose_name='Точка входа (заполняется автоматически)'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='entry_source',
            field=models.CharField(blank=True, default='', editable=False, help_text='Имя zip, из которого распакован пакет (служебное).', max_length=255),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='package',
            field=models.FileField(blank=True, help_text='Для типа «Слайды»: zip-экспорт курса iSpring/xAPI. После сохранения распаковывается автоматически.', null=True, upload_to='course_packages/zips/', verbose_name='Пакет слайдов (zip, iSpring)'),
        ),
    ]
