# Generated by Django 5.2.15 on 2026-07-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_course_module_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='card',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='products/derived/', verbose_name='Копия 400'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='derived_from',
            field=models.CharField(blank=True, default='', editable=False, help_text='Имя оригинала, из которого сделаны копии (служебное).', max_length=500),
        ),
        migrations.AddField(
            model_name='productimage',
            name='main',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='products/derived/', verbose_name='Копия 1200'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumb',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='products/derived/', verbose_name='Копия 160'),
        ),
    ]
