# Generated by Django 5.2.15 on 2026-07-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_product_image_derivatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Снятая галочка убирает товар из публичной выдачи API (и из витрины при следующей пересборке). Черновики/скрытые позиции держите неактивными.', verbose_name='Активен'),
        ),
    ]
