# Generated by Django 5.2 on 2026-07-12 17:34

import catalog.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='card',
            field=models.ImageField(blank=True, editable=False, null=True, storage=catalog.storage.ContentAddressedStorage(), upload_to='products/derived/', verbose_name='Копия 400'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=catalog.storage.ContentAddressedStorage(), upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='main',
            field=models.ImageField(blank=True, editable=False, null=True, storage=catalog.storage.ContentAddressedStorage(), upload_to='products/derived/', verbose_name='Копия 1200'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='thumb',
            field=models.ImageField(blank=True, editable=False, null=True, storage=catalog.storage.ContentAddressedStorage(), upload_to='products/derived/', verbose_name='Копия 160'),
        ),
    ]
