# Generated by Django 5.2 on 2026-07-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_product_image_cas_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilitySystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напр. «Straumann BLT».', max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, help_text='Оставьте пустым — сгенерируется автоматически из названия (транслитерацией).', max_length=255, unique=True, verbose_name='Slug')),
                ('group', models.CharField(blank=True, help_text='Напр. «Имплантация», «Ортодонтия». Для порядка и группировки в админке.', max_length=255, verbose_name='Группа/ось')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Система совместимости',
                'verbose_name_plural': 'Системы совместимости',
                'ordering': ['group', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='fitment_type',
            field=models.CharField(blank=True, choices=[('original', 'Оригинал'), ('compatible', 'Совместимый')], help_text='Обязательно, если указана хотя бы одна система совместимости.', max_length=16, verbose_name='Оригинал / совместимый'),
        ),
        migrations.AddField(
            model_name='product',
            name='compatibility_systems',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.compatibilitysystem', verbose_name='Системы совместимости'),
        ),
    ]
