# Generated by Django 5.2 on 2026-07-24 07:58

import catalog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_compatibility_systems'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_color',
            field=models.CharField(blank=True, help_text='Цвет образца в переключателе, напр. #C8A165. Пусто — чип останется текстовым (наборы, фасовки и т.п.).', max_length=7, validators=[catalog.utils.validate_hex_color], verbose_name='Цвет варианта (HEX)'),
        ),
    ]
