# Generated by Django 5.2 on 2026-08-18 12:56

import catalog.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_product_variant_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.PositiveIntegerField(default=0, verbose_name='Текущее значение')),
            ],
            options={
                'verbose_name': 'Счётчик номеров кейсов',
                'verbose_name_plural': 'Счётчик номеров кейсов',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.PositiveIntegerField(blank=True, editable=False, help_text='Сквозной номер, присваивается автоматически и не меняется.', null=True, unique=True, verbose_name='Номер кейса')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='Slug')),
                ('slug_locked', models.BooleanField(default=False, help_text='Ставится автоматически при первой публикации; дальше slug меняется только вручную.', verbose_name='Slug зафиксирован')),
                ('body_html', models.TextField(blank=True, verbose_name='Тело кейса (HTML)')),
                ('case_profile', models.CharField(blank=True, choices=[('clinical', 'Клинический'), ('lab', 'Лабораторный'), ('joint', 'Совместный')], db_index=True, editable=False, help_text='Вычисляется из аудиторий.', max_length=16, verbose_name='Профиль')),
                ('author_line', models.CharField(blank=True, max_length=255, verbose_name='Автор (строкой)')),
                ('cover', models.ImageField(blank=True, null=True, storage=catalog.storage.ContentAddressedStorage(), upload_to='cases/covers/', verbose_name='Обложка')),
                ('cover_thumb', models.ImageField(blank=True, editable=False, null=True, storage=catalog.storage.ContentAddressedStorage(), upload_to='cases/covers/')),
                ('cover_og', models.ImageField(blank=True, editable=False, null=True, storage=catalog.storage.ContentAddressedStorage(), upload_to='cases/covers/')),
                ('tooth_scope', models.CharField(choices=[('teeth', 'Отдельные зубы'), ('arch', 'Челюсть'), ('full_mouth', 'Полный рот')], default='teeth', max_length=16, verbose_name='Область')),
                ('teeth', models.JSONField(blank=True, default=list, verbose_name='Зубы (FDI)')),
                ('arches', models.JSONField(blank=True, default=list, verbose_name='Челюсти')),
                ('tooth_groups', models.JSONField(blank=True, default=list, editable=False)),
                ('tooth_sides', models.JSONField(blank=True, default=list, editable=False)),
                ('dentition', models.JSONField(blank=True, default=list, editable=False)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве')], db_index=True, default='draft', max_length=16, verbose_name='Статус')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Опубликован')),
                ('is_featured', models.BooleanField(default=False, help_text='Если есть избранные — в корне раздела показываются они, иначе последние по дате.', verbose_name='На витрину раздела')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('meta_description', models.CharField(blank=True, max_length=320, verbose_name='SEO description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audiences', models.ManyToManyField(blank=True, related_name='cases', to='catalog.audience', verbose_name='Аудитории')),
                ('directions', models.ManyToManyField(blank=True, related_name='cases', to='catalog.direction', verbose_name='Направления')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('image', models.ImageField(storage=catalog.storage.ContentAddressedStorage(), upload_to='cases/media/', verbose_name='Изображение')),
                ('thumb', models.ImageField(blank=True, editable=False, null=True, storage=catalog.storage.ContentAddressedStorage(), upload_to='cases/media/')),
                ('preview', models.ImageField(blank=True, editable=False, null=True, storage=catalog.storage.ContentAddressedStorage(), upload_to='cases/media/')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='Подпись')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt-текст')),
                ('show_in_gallery', models.BooleanField(default=True, help_text='Снимите, если картинка нужна только внутри текста.', verbose_name='Показывать в галерее')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.case')),
            ],
            options={
                'verbose_name': 'Изображение кейса',
                'verbose_name_plural': 'Изображения кейса',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.case')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Товар кейса',
                'verbose_name_plural': 'Товары кейса',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', 'published_at'], name='catalog_cas_status_bfe67b_idx'),
        ),
        migrations.AddConstraint(
            model_name='caseproduct',
            constraint=models.UniqueConstraint(fields=('case', 'product'), name='uniq_case_product'),
        ),
    ]
